{% set name = "pysindy" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a619980319d48ef0bfb364cfdf3a00f8ec585d69d32b92980bf79e89c43cf392

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - derivative >=0.6.2
    - numpy >=2.0
    - python >={{ python_min }}
    - scikit-learn >=1.1,!=1.5.0,!=1.6.0,!=1.7.1
    - scipy
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - pysindy

about:
  home: https://github.com/dynamicslab/pysindy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sparse Identification of Nonlinear Dynamics
  doc_url: https://pysindy.readthedocs.io
  dev_url: https://github.com/dynamicslab/pysindy

extra:
  recipe-maintainers:
    - moorepants
