{% set name = "pysindy" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 527d142f15f82321a78769641b6c545ed4148ba522ed595455f6ddcb43f74ece

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - derivative
    - numpy
    - python >={{ python_min }}
    - scikit-learn >=0.23
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pysindy

about:
  home: https://github.com/dynamicslab/pysindy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sparse Identification of Nonlinear Dynamics
  doc_url: https://pysindy.readthedocs.io
  dev_url: https://github.com/dynamicslab/pysindy

extra:
  recipe-maintainers:
    - moorepants
