{% set name = "pysindy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54972fe6d7a0d204c364e9c3de143e4e2d42d96f255e13adf19810a2b4319bc5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - numpy
    - python
    - scikit-learn >=0.23
    - scipy

test:
  imports:
    - pysindy

about:
  home: https://github.com/dynamicslab/pysindy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sparse Identification of Nonlinear Dynamics
  doc_url: https://pysindy.readthedocs.io
  dev_url: https://github.com/dynamicslab/pysindy

extra:
  recipe-maintainers:
    - moorepants
