{% set name = "pysindy" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 002323505f4bf5d64901e9a0461229bec78aac1344ccd9e36da90415165644d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - derivative
    - numpy
    - python
    - scikit-learn >=0.23
    - scipy

test:
  imports:
    - pysindy

about:
  home: https://github.com/dynamicslab/pysindy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sparse Identification of Nonlinear Dynamics
  doc_url: https://pysindy.readthedocs.io
  dev_url: https://github.com/dynamicslab/pysindy

extra:
  recipe-maintainers:
    - moorepants
