{% set name = "pysindy" %}
{% set version = "1.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a99c99b7a1e032e53113e2174abcf22d04ce1f0404deb8994fc4e3b6d34c7820

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - cmake
    - derivative
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scikit-learn >=0.23
    - scipy
    - scs >=2.1,!=2.1.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - pysindy

about:
  home: https://github.com/dynamicslab/pysindy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sparse Identification of Nonlinear Dynamics
  doc_url: https://pysindy.readthedocs.io
  dev_url: https://github.com/dynamicslab/pysindy

extra:
  recipe-maintainers:
    - moorepants
